import datetime
dctJson1 = {
        "mix_6_mode" : False,
        "mix_2_mode" : False,
        "dia_1_dmz" : 0.0,
        "Screw_Compund_Main_EX" : "",
        "spark_enable" : False,
        "dia_1_stable_kp" : 0.0,
        "Tooling_Sleeve" : "",
        "ratio_Cap_tension" : 0.0,
        "dia_1_max_tol" : 0.0,
        "prelength" : 148800.0,
        "ratio_sync" : 0.0,
        "ratio_ex1" : 0.0,
        "ratio_ex2" : 0.0,
        "ratio_ex3" : 0.0,
        "preset_ex2_z4" : 0,
        "Prod_Code" : "ORDER-BPH-11",
        "mix_5_mode" : False,
        "Executed" : "1970-01-01T08:00:00.000+08:00",
        "preset_ex1_z10" : 0,
        "mix_1_ratio" : 0.0,
        "Core_Colors" : "",
        "ratio_lsp_slave" : 0.0,
        "mix_4_mode" : False,
        "finlength" : 150000.0,
        "dia_1_OD" : 0.0,
        "Copper_Type" : "",
        "ratio_lsp" : 0.0,
        "Priority" : 0,
        "dia_1_min_tol" : 0.0,
        "dia_1_unstable_kp" : 0.0,
        "dia_2_unstable_kp" : 0.0,
        "preset_ex3_z10" : 0,
        "mix_1_mode" : False,
        "Screw_Main_EX" : "",
        "Tooling_Pin" : "",
        "preset_ex1_z4" : 0,
        "preset_ex1_z5" : 0,
        "preset_ex1_z6" : 0,
        "preset_ex1_z7" : 0,
        "preset_ex1_z1" : 0,
        "preset_ex1_z2" : 0,
        "preset_ex1_z3" : 0,
        "Standby" : "1970-01-01T08:00:00.000+08:00",
        "preset_ex1_z8" : 0,
        "preset_ex1_z9" : 0,
        "dia_2_min_tol" : 0.0,
        "Core_Prod_Code" : "",
        "Tooling_Die" : "",
        "dia_2_OD" : 0.0,
        "mix_6_ratio" : 0.0,
        "mix_3_ratio" : 0.0,
        "mix_3_mode" : False,
        "Status" : 1,
        "Screw_Compund_Aux_EX" : "",
        "preset_ex3_z8" : 0,
        "preset_ex3_z9" : 0,
        "preset_ex3_z2" : 0,
        "preset_ex3_z3" : 0,
        "preset_ex3_z1" : 0,
        "preset_ex3_z6" : 0,
        "preset_ex3_z7" : 0,
        "preset_ex3_z4" : 0,
        "preset_ex3_z5" : 0,
        "dia_1_ID" : 0.0,
        "mix_2_ratio" : 0.0,
        "spark_set_volt" : 0.0,
        "preset_ex2_z1" : 0,
        "preset_ex2_z3" : 0,
        "preset_ex2_z2" : 0,
        "preset_ex2_z5" : 0,
        "spark_mode" : 0,
        "preset_ex2_z7" : 0,
        "preset_ex2_z6" : 0,
        "preset_ex2_z9" : 0,
        "preset_ex2_z8" : 0,
        "dia_2_ID" : 0.0,
        "dia_2_dmz" : 0.0,
        "mix_5_ratio" : 0.0,
        "throughput_Mix_1" : 0.0,
        "throughput_Mix_2" : 0.0,
        "throughput_Mix_3" : 0.0,
        "throughput_Mix_4" : 0.0,
        "throughput_Mix_5" : 0.0,
        "throughput_Mix_6" : 0.0,
        "dia_2_max_tol" : 0.0,
        "Screw_Aux_EX" : "",
        "Object_ID" : "",
        "dia_2_stable_kp" : 0.0,
        "Description" : "BPH - Testing #11",
        "preset_ex2_z10" : 0,
        "Estimate_Time" : "1970-01-01T08:00:00.000+08:00",
        "material_ex3" : 0,
        "material_ex2" : 0,
        "material_ex1" : 0,
        "Launched" : "1970-01-01T08:00:00.000+08:00",
        "modes_ex1" : 0,
        "modes_ex3" : 0,
        "modes_ex2" : 0,
        "mix_4_ratio" : 0.0
    }

dctJson2 = {
        "Copper_Type" : "",
        "Core_Colors" : "",
        "Core_Prod_Code" : "",
        "Description" : "",
        "Estimate_Time" : "2020-01-13T13:51:23.840+08:00",
        "Executed" : "2020-01-13T13:51:23.840+08:00",
        "Launched" : "2020-01-13T13:51:23.840+08:00",
        "Object_ID" : "",
        "Priority" : 0,
        "Prod_Code" : "ORDER-SMF-15",
        "Screw_Aux_EX" : "",
        "Screw_Compund_Aux_EX" : "",
        "Screw_Compund_Main_EX" : "",
        "Screw_Main_EX" : "",
        "Standby" : "2020-01-13T13:51:23.840+08:00",
        "Status" : 1,
        "Tooling_Die" : "",
        "Tooling_Pin" : "",
        "Tooling_Sleeve" : "",
        "material_ex1" : 0,
        "material_ex2" : 0,
        "material_ex3" : 0,
        "mix_6_mode" : False,
        "mix_2_mode" : False,
        "mix_5_mode" : False,
        "mix_1_ratio" : 0,
        "mix_4_mode" : False,
        "mix_1_mode" : False,
        "mix_6_ratio" : 0,
        "mix_3_ratio" : 0,
        "mix_3_mode" : False,
        "mix_2_ratio" : 0,
        "mix_5_ratio" : 0,
        "mix_4_ratio" : 0,
        "dia_1_dmz" : 0,
        "dia_1_stable_kp" : 1.12345,
        "dia_1_OD" : 0,
        "dia_1_min_tol" : 0,
        "dia_1_unstable_kp" : 0,
        "dia_2_unstable_kp" : 0,
        "dia_2_min_tol" : 0,
        "dia_2_OD" : 0,
        "dia_1_max_tol" : 0,
        "dia_2_ID" : 0,
        "dia_2_max_tol" : 0,
        "dia_1_ID" : 0,
        "dia_2_stable_kp" : 0,
        "dia_2_dmz" : 0,
        "spark_enable" : False,
        "spark_set_volt" : 0,
        "spark_mode" : 0,
        "ratio_Cap_tension" : 0,
        "ratio_sync" : 0,
        "ratio_ex1" : 0,
        "ratio_ex2" : 0,
        "ratio_ex3" : 0,
        "ratio_lsp_slave" : 0,
        "ratio_lsp" : 0,
        "prelength" : 0,
        "finlength" : 0,
        "preset_ex2_z4" : 0,
        "preset_ex1_z10" : 0,
        "preset_ex3_z10" : 0,
        "preset_ex1_z4" : 0,
        "preset_ex1_z5" : 0,
        "preset_ex1_z6" : 0,
        "preset_ex1_z7" : 0,
        "preset_ex1_z1" : 0,
        "preset_ex1_z2" : 0,
        "preset_ex1_z3" : 0,
        "preset_ex1_z8" : 0,
        "preset_ex1_z9" : 0,
        "preset_ex3_z8" : 0,
        "preset_ex3_z9" : 0,
        "preset_ex3_z2" : 0,
        "preset_ex3_z3" : 0,
        "preset_ex3_z1" : 0,
        "preset_ex3_z6" : 0,
        "preset_ex3_z7" : 0,
        "preset_ex3_z4" : 0,
        "preset_ex3_z5" : 0,
        "preset_ex2_z1" : 0,
        "preset_ex2_z3" : 0,
        "preset_ex2_z2" : 0,
        "preset_ex2_z5" : 0,
        "preset_ex2_z7" : 0,
        "preset_ex2_z6" : 0,
        "preset_ex2_z9" : 0,
        "preset_ex2_z8" : 0,
        "modes_ex1" : 0,
        "preset_ex2_z10" : 0,
        "modes_ex3" : 0,
        "modes_ex2" : 0,
        "throughput_Mix_1" : 0,
        "throughput_Mix_2" : 0,
        "throughput_Mix_3" : 0,
        "throughput_Mix_4" : 0,
        "throughput_Mix_5" : 0,
        "throughput_Mix_6" : 0
    }


if __name__ == "__main__":
    lstKeysInJson1 = list()
    lstKeysInJson2 = list()
    lstTypeInJson1 = list()
    for k1, v1 in dctJson1.items():
        if k1 not in dctJson2.keys():
            lstKeysInJson1.append(k1)
        else:
            if type(dctJson1[k1]) != type(dctJson2[k1]):
                lstTypeInJson1.append({k1:type(dctJson1[k1])})

    
    for k2 in dctJson2.keys():
        if k2 not in dctJson1.keys():
            lstKeysInJson2.append(k2)
    
    print("lstKeysInJson1:", lstKeysInJson1)
    print()
    print("lstKeysInJson2:", lstKeysInJson2)
    print()

    # =========================================
    
    print("lstTypeInJson1:", lstTypeInJson1)
    

