import datetime
# dctJson1 = {
#         "mix_6_mode" : False,
#         "mix_2_mode" : False,
#         "dia_1_dmz" : 0.0,
#         "Screw_Compund_Main_EX" : "",
#         "spark_enable" : False,
#         "dia_1_stable_kp" : 0.0,
#         "Tooling_Sleeve" : "",
#         "ratio_Cap_tension" : 0.0,
#         "dia_1_max_tol" : 0.0,
#         "prelength" : 148800.0,
#         "ratio_sync" : 0.0,
#         "ratio_ex1" : 0.0,
#         "ratio_ex2" : 0.0,
#         "ratio_ex3" : 0.0,
#         "preset_ex2_z4" : 0,
#         "Prod_Code" : "ORDER-BPH-11",
#         "mix_5_mode" : False,
#         "Executed" : "1970-01-01T08:00:00.000+08:00",
#         "preset_ex1_z10" : 0,
#         "mix_1_ratio" : 0.0,
#         "Core_Colors" : "",
#         "ratio_lsp_slave" : 0.0,
#         "mix_4_mode" : False,
#         "finlength" : 150000.0,
#         "dia_1_OD" : 0.0,
#         "Copper_Type" : "",
#         "ratio_lsp" : 0.0,
#         "Priority" : 0,
#         "dia_1_min_tol" : 0.0,
#         "dia_1_unstable_kp" : 0.0,
#         "dia_2_unstable_kp" : 0.0,
#         "preset_ex3_z10" : 0,
#         "mix_1_mode" : False,
#         "Screw_Main_EX" : "",
#         "Tooling_Pin" : "",
#         "preset_ex1_z4" : 0,
#         "preset_ex1_z5" : 0,
#         "preset_ex1_z6" : 0,
#         "preset_ex1_z7" : 0,
#         "preset_ex1_z1" : 0,
#         "preset_ex1_z2" : 0,
#         "preset_ex1_z3" : 0,
#         "Standby" : "1970-01-01T08:00:00.000+08:00",
#         "preset_ex1_z8" : 0,
#         "preset_ex1_z9" : 0,
#         "dia_2_min_tol" : 0.0,
#         "Core_Prod_Code" : "",
#         "Tooling_Die" : "",
#         "dia_2_OD" : 0.0,
#         "mix_6_ratio" : 0.0,
#         "mix_3_ratio" : 0.0,
#         "mix_3_mode" : False,
#         "Status" : 1,
#         "Screw_Compund_Aux_EX" : "",
#         "preset_ex3_z8" : 0,
#         "preset_ex3_z9" : 0,
#         "preset_ex3_z2" : 0,
#         "preset_ex3_z3" : 0,
#         "preset_ex3_z1" : 0,
#         "preset_ex3_z6" : 0,
#         "preset_ex3_z7" : 0,
#         "preset_ex3_z4" : 0,
#         "preset_ex3_z5" : 0,
#         "dia_1_ID" : 0.0,
#         "mix_2_ratio" : 0.0,
#         "spark_set_volt" : 0.0,
#         "preset_ex2_z1" : 0,
#         "preset_ex2_z3" : 0,
#         "preset_ex2_z2" : 0,
#         "preset_ex2_z5" : 0,
#         "spark_mode" : 0,
#         "preset_ex2_z7" : 0,
#         "preset_ex2_z6" : 0,
#         "preset_ex2_z9" : 0,
#         "preset_ex2_z8" : 0,
#         "dia_2_ID" : 0.0,
#         "dia_2_dmz" : 0.0,
#         "mix_5_ratio" : 0.0,
#         "throughput_Mix_1" : 0.0,
#         "throughput_Mix_2" : 0.0,
#         "throughput_Mix_3" : 0.0,
#         "throughput_Mix_4" : 0.0,
#         "throughput_Mix_5" : 0.0,
#         "throughput_Mix_6" : 0.0,
#         "dia_2_max_tol" : 0.0,
#         "Screw_Aux_EX" : "",
#         "Object_ID" : "",
#         "dia_2_stable_kp" : 0.0,
#         "Description" : "BPH - Testing #11",
#         "preset_ex2_z10" : 0,
#         "Estimate_Time" : "1970-01-01T08:00:00.000+08:00",
#         "material_ex3" : 0,
#         "material_ex2" : 0,
#         "material_ex1" : 0,
#         "Launched" : "1970-01-01T08:00:00.000+08:00",
#         "modes_ex1" : 0,
#         "modes_ex3" : 0,
#         "modes_ex2" : 0,
#         "mix_4_ratio" : 0.0
#     }

dctJson1 = {
    "modes_ex1":0,
    "preset_ex1_z1":1,
    "preset_ex1_z2":2,
    "preset_ex1_z3":3,
    "preset_ex1_z4":4,
    "preset_ex1_z5":5,
    "preset_ex1_z6":6,
    "preset_ex1_z7":7,
    "preset_ex1_z8":8,
    "preset_ex1_z9":9,
    "preset_ex1_z10":10,
    "modes_ex2":11,
    "preset_ex2_z1":12,
    "preset_ex2_z2":13,
    "preset_ex2_z3":14,
    "preset_ex2_z4":15,
    "preset_ex2_z5":16,
    "preset_ex2_z6":17,
    "preset_ex2_z7":18,
    "preset_ex2_z8":19,
    "preset_ex2_z9":20,
    "preset_ex2_z10":21,
    "modes_ex3":22,
    "preset_ex3_z1":23,
    "preset_ex3_z2":24,
    "preset_ex3_z3":25,
    "preset_ex3_z4":26,
    "preset_ex3_z5":27,
    "preset_ex3_z6":28,
    "preset_ex3_z7":29,
    "preset_ex3_z8":30,
    "preset_ex3_z9":31,
    "preset_ex3_z10":32,
    "dia_1_OD":33,
    "dia_1_ID":34,
    "dia_1_stable_kp":35,
    "dia_1_unstable_kp":36,
    "dia_1_max_tol":37,
    "dia_1_min_tol":38,
    "dia_1_dmz":39,
    "dia_2_OD":40,
    "dia_2_ID":41,
    "dia_2_stable_kp":42,
    "dia_2_unstable_kp":43,
    "dia_2_max_tol":44,
    "dia_2_min_tol":45,
    "dia_2_dmz":46,
    "mix_1_mode":47,
    "mix_1_ratio":48,
    "mix_2_mode":49,
    "mix_2_ratio":50,
    "mix_3_mode":51,
    "mix_3_ratio":52,
    "mix_4_mode":53,
    "mix_4_ratio":54,
    "mix_5_mode":55,
    "mix_5_ratio":56,
    "mix_6_mode":57,
    "mix_6_ratio":58,
    "throughput_Mix_1":59,
    "throughput_Mix_2":60,
    "throughput_Mix_3":61,
    "throughput_Mix_4":62,
    "throughput_Mix_5":63,
    "throughput_Mix_6":64,
    "ratio_ex1":65,
    "ratio_ex2":66,
    "ratio_ex3":67,
    "ratio_lsp":68,
    "ratio_sync":69,
    "ratio_lsp_slave":70,
    "ratio_Cap_tension":71,
    "prelength":72,
    "finlength":73,
    "spark_enable":74,
    "spark_mode":75,
    "spark_set_volt":76,
    "Standby":77,
    "Launched":78,
    "Executed":79,
    "Estimate_Time":80,
    "Status":81,
    "Priority":82,
    "Order_No_ERP":83,
    "Item_Number_ERP":84,
    "Description":85,
    "Product_Code":86,
    "Core_Product_Code":87,
    "6B_Core_Colors":88,
    "12B_Core_Colors":89,
    "18B_Core_Colors":90,
    "24B_Core_Colors":91,
    "Copper_Size":92,
    "Copper_type":93,
    "Job_order_denominator":94,
    "Job_order_fraction ":95,
    "Tooling[0]":96,
    "Tooling[1]":97,
    "Tooling[2]":98,
    "Tooling[3]":99,
    "Tooling[4]":100,
    "material[1]":101,
    "material[2]":102,
    "material[3]":103,
    "Main_EX":104,
    "Aux_EX":105,
    "Compund_Main_EX":106,
    "Compund_Aux_EX":107,
    "Input_Batch_No":108,
    "Input_Target_Length":109,
    "Input_specification":110,
    "Input_Operator":111,
    "Input_Data":112,
    "Input_Serial_of_input":113,
    "Input_number_concurrently":114,
    "Output_Batch_No":115,
    "Output_Target_Length":116,
    "Output_specification":117,
    "Output_Operator":118,
    "Output_Data":119,
    "Output_Serial_of_output":120,
    "Output_idx_of_head":121,
    "Object_ID":122

}

dctJson2 = {
        "Item_Number_ERP" : "13",
        "Description" : "13",
        "Core_Product_Code" : "13",
        "Copper_Size" : "13",
        "Copper_type" : "13",
        "Tooling[0]" : "13",
        "Tooling[1]" : "13",
        "Tooling[2]" : "13",
        "Tooling[3]" : "13",
        "Tooling[4]" : "13",
        "material[1]" : "13",
        "material[2]" : "13",
        "material[3]" : "13",
        "Input_Batch_No" : "13",
        "Input_Target_Length" : "13",
        "Input_specification" : "13",
        "Input_Operator" : "13",
        "Input_Data" : "13",
        "Input_Serial_of_input" : "13",
        "Input_number_concurrently" : "13",
        "Used_PayOff" : "13",
        "Output_Batch_No" : "13",
        "Output_Target_Length" : "13",
        "Output_specification" : "13",
        "Output_Operator" : "13",
        "Output_Data" : "13",
        "Output_Serial_of_output" : "3",
        "Output_idx_of_head" : "13",
        "Order_No_ERP" : "7",
        "Product_Code" : "7",
        "6B_Core_Colors" : "",
        "12B_Core_Colors" : "",
        "18B_Core_Colors" : "",
        "24B_Core_Colors" : "",
        "Main_EX" : "",
        "Aux_EX" : "",
        "Compund_Main_EX" : "",
        "Compund_Aux_EX" : "",
        "Object_ID" : "",
        "dia_1_ID" : 0,
        "dia_1_OD" : 0,
        "dia_1_dmz" : 0,
        "dia_1_max_tol" : 0,
        "dia_1_min_tol" : 0,
        "dia_1_stable_kp" : 0,
        "dia_1_unstable_kp" : 0,
        "dia_2_ID" : 0,
        "dia_2_OD" : 0,
        "dia_2_dmz" : 0,
        "dia_2_max_tol" : 0,
        "dia_2_min_tol" : 0,
        "dia_2_stable_kp" : 0,
        "dia_2_unstable_kp" : 0,
        "finlength" : 0,
        "prelength" : 0,
        "mix_1_mode" : False,
        "mix_1_ratio" : 0,
        "mix_2_mode" : False,
        "mix_2_ratio" : 0,
        "mix_3_mode" : False,
        "mix_3_ratio" : 0,
        "mix_4_mode" : False,
        "mix_4_ratio" : 0,
        "mix_5_mode" : False,
        "mix_5_ratio" : 0,
        "mix_6_mode" : False,
        "mix_6_ratio" : 0,
        "modes_ex1" : 0,
        "modes_ex2" : 0,
        "modes_ex3" : 0,
        "preset_ex1_z1" : 0,
        "preset_ex1_z10" : 0,
        "preset_ex1_z2" : 0,
        "preset_ex1_z3" : 0,
        "preset_ex1_z4" : 0,
        "preset_ex1_z5" : 0,
        "preset_ex1_z6" : 0,
        "preset_ex1_z7" : 0,
        "preset_ex1_z8" : 0,
        "preset_ex1_z9" : 0,
        "preset_ex2_z1" : 0,
        "preset_ex2_z10" : 0,
        "preset_ex2_z2" : 0,
        "preset_ex2_z3" : 0,
        "preset_ex2_z4" : 0,
        "preset_ex2_z5" : 0,
        "preset_ex2_z6" : 0,
        "preset_ex2_z7" : 0,
        "preset_ex2_z8" : 0,
        "preset_ex2_z9" : 0,
        "preset_ex3_z1" : 0,
        "preset_ex3_z10" : 0,
        "preset_ex3_z2" : 0,
        "preset_ex3_z3" : 0,
        "preset_ex3_z4" : 0,
        "preset_ex3_z5" : 0,
        "preset_ex3_z6" : 0,
        "preset_ex3_z7" : 0,
        "preset_ex3_z8" : 0,
        "preset_ex3_z9" : 0,
        "ratio_Cap_tension" : 0,
        "ratio_ex1" : 0,
        "ratio_ex2" : 0,
        "ratio_ex3" : 0,
        "ratio_lsp" : 0,
        "ratio_lsp_slave" : 0,
        "ratio_sync" : 0,
        "spark_enable" : False,
        "spark_mode" : 0,
        "spark_set_volt" : 0,
        "throughput_Mix_1" : 0,
        "throughput_Mix_2" : 0,
        "throughput_Mix_3" : 0,
        "throughput_Mix_4" : 0,
        "throughput_Mix_5" : 0,
        "throughput_Mix_6" : 0,
        "Estimate_Time" : "2020-02-24T03:03:08.506Z",
        "Executed" : "2020-02-24T03:03:08.506Z",
        "Launched" : "2020-02-24T03:03:08.506Z",
        "Standby" : "2020-02-24T03:03:08.506Z",
        "Priority" : 0,
        "Status" : 1,
        "jobCode" : "13"
    }


if __name__ == "__main__":
    lstKeysInJson1 = list()
    lstKeysInJson2 = list()
    lstTypeInJson1 = list()
    for k1, v1 in dctJson1.items():
        if k1 not in dctJson2.keys():
            lstKeysInJson1.append(k1)
        else:
            if type(dctJson1[k1]) != type(dctJson2[k1]):
                lstTypeInJson1.append({k1:type(dctJson1[k1])})

    
    for k2 in dctJson2.keys():
        if k2 not in dctJson1.keys():
            lstKeysInJson2.append(k2)
    
    print("lstKeysInJson1:", lstKeysInJson1)
    print()
    print("lstKeysInJson2:", lstKeysInJson2)
    print()

    # =========================================
    
    # print("lstTypeInJson1:", lstTypeInJson1)
    

