"""
Django settings for Django_Attendance project.

Generated by 'django-admin startproject' using Django 2.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'agm#-=-x^q^@rl94fxs5$-lh^!vc2&&i&h(q#cq73k2hr(=9%('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "attendances.apps.AttendancesConfig",
    "accounts.apps.AccountsConfig",
    'crispy_forms',
    # "mongoengine",                                            # Leamon Mongoengine
    'mongoengine.django.mongo_auth',                            # Leamon Mongoengine
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Django_Attendance.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ["templates"],                                          # Leamon If you want django searches the app root directories, must add this line.
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Django_Attendance.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

# If you are not using another Database backend, 
# you may need to add a dummy database backend to settings.py 
# eg:


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.dummy'
    }
}

import mongoengine
mongoengine.connect('mytestdb', host='10.101.100.95', port=27017)

# # add session
# # If you want MongoDB to also handle your session tracking, 
# # add the following code to the settings.py file:

# SESSION_ENGINE = 'mongoengine.django.sessions'
# SESSION_SERIALIZER = 'mongoengine.django.sessions.BSONSerializer'     # Only necessary in DJango 1.6

# # add authentication
AUTHENTICATION_BACKENDS = (
    # 'mongoengine.django.auth.MongoEngineBackend',
    'django_mongoengine.mongo_auth.backends.MongoEngineBackend',
)

AUTH_USER_MODEL = 'mongo_auth.MongoUser'

TEMPLATE_CONTEXT_PROCESSORS = (
    'django.contrib.auth.context_processors.auth',
)

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'
TIME_ZONE = "Asia/Taipei"


USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'                              # You can find the .css file by typing in url. Ex: http://localhost:8000/static/attendances/myTable.css

STATICFILES_DIRS = (                                # Other than those storing in each app's static directory,
    os.path.join(BASE_DIR, "common_static"),        # also find in directories defined in STATICFILES_DIRS.
)

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

CRISPY_TEMPLATE_PACK = 'bootstrap4'

LOGIN_REDIRECT_URL = 'app-home'     # If user logins successfully, then redirect them to the "blog-home" page. Default: /accounts/profile/
LOGIN_URL = 'accounts:login'        # If user requests the page which needs to be authenticated, but they haven't logged in yet, 
                                    # then direct them to the url --> /login/   default: /accounts/login/