# Generated by Django 2.1.3 on 2018-12-06 06:21

from django.db import migrations, models
import djongo.models.fields
import mongos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', djongo.models.fields.EmbeddedModelField(model_container=mongos.models.Blog, null=True)),
                ('meta_data', djongo.models.fields.EmbeddedModelField(model_container=mongos.models.MetaData, null=True)),
                ('headline', models.CharField(max_length=255)),
                ('body_text', models.TextField()),
                ('authors', djongo.models.fields.ArrayModelField(model_container=mongos.models.Author)),
                ('n_comments', models.IntegerField()),
            ],
        ),
    ]
