# Generated by Django 2.1.3 on 2018-12-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mongos', '0002_delete_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
