# Generated by Django 2.1.3 on 2018-11-27 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('office_hours', models.TimeField()),
                ('off_hours', models.TimeField()),
                ('clockin_time', models.TimeField()),
                ('clockout_time', models.TimeField()),
                ('clockin_status', models.CharField(max_length=20)),
                ('clockout_status', models.CharField(max_length=20)),
                ('total_working_hours', models.FloatField()),
                ('abnormal_hours', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
